-------------------------------------------------------------------------------
-- CREATE DATE - Julho 2026
-- DESCRIPTION - DML de criacao de registros base na tabela UNITS
-------------------------------------------------------------------------------
-- MASSA
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 1, 'Miligrama', 'mg', 10, 0.001);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 1, 'Grama', 'g', 20, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 1, 'Quilograma', 'kg', 30, 1000);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 1, 'Tonelada', 't', 40, 1000000);

-- VOLUME
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 2, 'Mililitro', 'ml', 10, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 2, 'Litro', 'l', 20, 1000);

-- CONTAGEM
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 3, 'Unidade', 'un', 10, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 3, 'Rolo', 'rolo', 20, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 3, 'Pacote', 'pct', 30, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 3, 'Caixa', 'cx', 40, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 3, 'Garrafa', 'garrafa', 50, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 3, 'Lata', 'lata', 60, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 3, 'Capsula', 'caps', 70, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 3, 'Envelope', 'env', 80, 1);
INSERT INTO UNITS (ID, UNIT_GROUP_ID, NAME, SYMBOL, DISPLAY_ORDER, BASE_FACTOR) VALUES (SEQ_UNITS.nextval, 3, 'Sache', 'sache', 90, 1);
/