-------------------------------------------------------------------------------
-- CREATE DATE - Julho 2026
-- DESCRIPTION - DML de criacao de registros base na tabela UNIDADES_MEDIDA
-------------------------------------------------------------------------------
-- MASSA
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (1, 1, 'Miligrama', 'mg', 10, 0.001);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (2, 1, 'Grama', 'g', 20, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (3, 1, 'Quilograma', 'kg', 30, 1000);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (4, 1, 'Tonelada', 't', 40, 1000000);

-- VOLUME
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (5, 2, 'Mililitro', 'ml', 10, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (6, 2, 'Litro', 'l', 20, 1000);

-- CONTAGEM
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (7, 3, 'Unidade', 'un', 10, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (8, 3, 'Rolo', 'rolo', 20, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (9, 3, 'Pacote', 'pct', 30, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (10, 3, 'Caixa', 'cx', 40, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (11, 3, 'Garrafa', 'garrafa', 50, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (12, 3, 'Lata', 'lata', 60, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (13, 3, 'Capsula', 'caps', 70, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (14, 3, 'Envelope', 'env', 80, 1);
INSERT INTO UNIDADES_MEDIDA (ID, GRUPO_MEDIDA_ID, NOME, SIGLA, ORDEM_EXIBICAO, FATOR_BASE) VALUES (15, 3, 'Sache', 'sache', 90, 1);
/